name: Update Website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ARM64 # Korbs' Web Server

    steps:
      - uses: actions/checkout@v3
      - run: cp -R * /usr/share/nginx/nlauncher/
